import { Inter } from 'next/font/google'
import './globals.css'
import TopHeader from '@/Components/SharedComponents/TopHeader'
import Navber from '@/Components/SharedComponents/Navber'
import Footer from '@/Components/SharedComponents/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=' w-full z-50'>
          <TopHeader />
          <Navber />
        </div>
        <div className='min-h-screen'>
        {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
