import { Inter } from 'next/font/google'
import './globals.css'
import TopHeader from '@/Components/TopHeader'
import Navber from '@/Components/Navber'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TopHeader />
      <Navber />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
