import { Inter } from 'next/font/google'
import './globals.css'
import TopHeader from '@/Components/TopHeader'
import Navber from '@/Components/Navber'
import Footer from '@/Components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='top-0 left-0 absolute w-full'>
          <TopHeader />
          <Navber />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
